/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ipn.mx.vistas;

import com.ipn.mx.conexion.OperacionDAO;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author Clemente
 */
public class VerOperaciones extends javax.swing.JFrame {

     String []encabezados= {"TIPO DE REPORTE","PERIODO DEL REPORTE","FOLIO","ORGANISMO SUPERVISOR","CLAVE DEL SUJETO OBLIGADO","LOCALIDAD",
         "CODIGO POSTAL DE LA SUCURSAL","TIPO DE OPERACION","INSTRUMENTO ETARIO","NUMERO DE CUENTA,CONTRATO U OPERACION","MONTO","MONEDA",
         "FECHA DE LA OPERACION","FECHA DE DETECCION","NACIONALIDAD","TIPO DE PERSONA","RAZON SOCIAL O DENOMINACION","NOMBRE",
         "APELLIDO PATERNO","APELLIDO MATERNO","RFC","CURP","FECHA NACIMIENTO O CONSTITUCION","DOMICILIO"
         ,"COLONIA","CIUDAD O POBLACION","TELEFONO","ACTIVIDAD ECONOMICA","CONSECUTIVO DE PERSONAS Y/O PERSONAS RELAIONADAS",
         "NUMERO DE CUENTA,CONTRATO,OPERACION,POLIZA O NUMERO DE SEGURIDAD SOCIAL","CLAVE DEL SUJETO OBLIGADO",
         "NOMBRE DEL TITULAR DE LA CUENTA","APELLIDO PATERNO","APELLIDO MATERNO","DESCRIPCION DE LA OPERACION",
         "RAZONES POR LAS QUE LA OPERACION SE CONSIDERA INUSUAL"};
     ResultSet rs;
     String tipoReporte="";     String fechaop="";              String domicilio="";            String razones="";
     String periodo="";         String fechadet="";             String colonia="";              String monto="";
     String folio="";           String nacionalidad="";         String ciudad="";               String numcuenta2="";
     String organosup="";       String tipopersona="";          String telefono="";
     String clave="";           String Razonsocial="";          String actividad="";
     String localidad="";       String nombre="";               String consecutivo="";
     String CPINM="";           String ApPat="";                String clave2="";
     String tipoOp="";          String ApMat="";                String nombre2="";
     String Instrumento="";     String RFC="";                  String appat2="";
     String numCuenta="";       String CURP="";                 String apmat2="";
     String moneda="";          String fechanac="";             String descripcion="";
     
    /**
     * Creates new form VerOperaciones
     */
    public VerOperaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Generar Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        try {                                         
            
            String nombrearchivo=JOptionPane.showInputDialog("Ingrese nomnbre para el reporte");;
            String rutaArchivo = "C:\\Users\\Clemente\\Documents\\NetBeansProjects\\PLD"+"/"+nombrearchivo+".xls";
            System.out.println(rutaArchivo);
            OperacionDAO d=new OperacionDAO();
            rs=d.DatosReportes();
            
             while(rs.next()){
                clave=rs.getString("clave");
                CPINM=rs.getString("codigoPostal");
                tipoOp=rs.getString("clavetipoOp");
                Instrumento=rs.getString("monetarioclave");
                numCuenta=rs.getString("numeroContrato");
                monto=rs.getString("monto");
                moneda=rs.getString("claveMoneda");
                fechaop=rs.getString("fechaOperacion");
                nacionalidad=rs.getString("paisOrigen");
                tipopersona=rs.getString("descripcion");
                Razonsocial=rs.getString("nombre");
                nombre=rs.getString("nombre");
                ApPat=rs.getString("apellido_Pat");
                ApMat=rs.getString("apellido_Mat");
                RFC=rs.getString("RFC");
                fechanac=rs.getString("fecha_nac");
                domicilio=rs.getString("calle");
                ciudad=rs.getString("localidad");
                telefono=rs.getString("numero_Telefono");
                actividad=rs.getString("folio");
                descripcion=rs.getString("descripcion");
                
             
            }
            
            
            try {
                File archivoXLS = new File(rutaArchivo);
                String []datos= {tipoReporte,periodo,folio,organosup,clave,localidad,CPINM,tipoOp,Instrumento,numCuenta,monto,moneda,fechaop,fechadet,
                     nacionalidad,tipopersona,Razonsocial,nombre,ApPat,ApMat,RFC,CURP,fechanac,domicilio,colonia,ciudad,telefono,actividad,
                    consecutivo,numcuenta2,clave2,nombre2,appat2,apmat2,descripcion,razones};
                
                if(archivoXLS.exists()) archivoXLS.delete();
                
                archivoXLS.createNewFile();
                
                
                Workbook libro = new HSSFWorkbook();
                
                FileOutputStream archivo = new FileOutputStream(archivoXLS);
                
                
                Sheet hoja = libro.createSheet("Reporte");
                
                
                for(int f=0;f<2;f++){
                    /* crear las filas*/
                    Row fila = hoja.createRow(f);
                    
                    for(int c=0;c<encabezados.length;c++){
                        /*Creamos la celda a partir de la fila actual*/
                        Cell celda = fila.createCell(c);
                        
                        /*Si la fila es la número 0, estableceremos los encabezados*/
                        if(f==0){
                            celda.setCellValue(encabezados[c]);
                        }else{
                            /*Si no es la primera fila establecemos un valor*/
                            celda.setCellValue(datos[c]);
                            System.out.println("tiene en :"+encabezados[c]+"el dato de:"+datos[c]+"\n");
                        }
                    }
                }
                
                /*Escribimos en el libro*/
                libro.write(archivo);
                /*Cerramos el flujo de datos*/
                archivo.close();
            } catch (IOException ex) {
                Logger.getLogger(VerOperaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
             Logger.getLogger(VerOperaciones.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerOperaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
