/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ipn.mx.vistas;

import com.ipn.mx.conexion.Conexion;
import com.ipn.mx.conexion.DocumentacionDao;
import com.mx.ipn.clases.AESDemo;
import com.mx.ipn.clases.MiPanel;
import com.mx.ipn.clases.Operacion;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Clemente
 */
public class VistasDocumentacion extends javax.swing.JFrame {
Conexion con=new Conexion();
    Connection reg=con.conectar();
    ResultSet rs;
PreparedStatement st;
JTable tabla;
int riesgoresidencia;
int idOP;
AESDemo d = new AESDemo ();

    
    Operacion c=new Operacion();
    /**
     * Creates new form VistasDocumentacion
     */
    public VistasDocumentacion() throws SQLException {
        initComponents();
        JPasswordField pwd = new JPasswordField(10);
         JOptionPane.showConfirmDialog(null, pwd,"Ingrese Contraseña",JOptionPane.OK_CANCEL_OPTION);
   
        while("".equals(new String(pwd.getPassword()))){
             JOptionPane.showMessageDialog(null,"Se necesita contraseña para continuar");
             JOptionPane.showConfirmDialog(null, pwd,"Ingrese Contraseña",JOptionPane.OK_CANCEL_OPTION);
        }
        d.addKey(new String(pwd.getPassword()));
        
         actualizarTabla();
         cargarOperacion();
          
        MiPanel p = new MiPanel();
        this.add( p , BorderLayout.CENTER);
        p.repaint();
        setLayout(null);
        setLocationRelativeTo(null);        // Centering on screen...
        setSize(900, 700);               // Setting dimensions...
        setTitle("SisPLD");
        setResizable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        comboOperacion = new javax.swing.JComboBox();
        jButton9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Aceptar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Seleccione el documento que el Cliente Entrego y Escriba el numero de Folio:");

        Aceptar.setForeground(new java.awt.Color(0, 153, 51));
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setForeground(new java.awt.Color(0, 153, 51));
        Cancelar.setText("Regresar");
        Cancelar.setActionCommand("");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setFillsViewportHeight(true);
        jTable2.setMinimumSize(new java.awt.Dimension(100, 100));
        jTable2.setOpaque(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Operacion "));
        jPanel6.setOpaque(false);

        jLabel12.setText("Contrato:");

        comboOperacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...." }));
        comboOperacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboOperacionMouseClicked(evt);
            }
        });
        comboOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOperacionActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 153, 51));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Seleccionar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(comboOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton9)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Registrar Documentación");

        Aceptar1.setBackground(new java.awt.Color(0, 153, 51));
        Aceptar1.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar1.setText("Nuevo");
        Aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aceptar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(432, 432, 432)
                                        .addComponent(Aceptar1)
                                        .addGap(28, 28, 28)
                                        .addComponent(Aceptar)
                                        .addGap(18, 18, 18)
                                        .addComponent(Cancelar))
                                    .addComponent(jLabel15)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Cancelar)
                    .addComponent(Aceptar1))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        int id = 0 ;
        boolean check  ;
        String folio = null;
        DocumentacionDao cn = new DocumentacionDao();
        DefaultTableModel dfm = new DefaultTableModel(){

            Class[] types = new Class[]{
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class,java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };
        tabla = this.jTable2;

        TableModel tableModel = tabla.getModel();
        int cols = tableModel.getColumnCount();
        int fils = tableModel.getRowCount();
        
        for(int i=0; i<fils; i++) {
            for(int j=0; j<cols;j++ ){
                if(j==0){
                    id = Integer.parseInt((String) tableModel.getValueAt(i,j));
                       System.out.println(id);
                }else if(j==2){
                //check = (boolean) tableModel.getValueAt(i, j);
                }else if(j==3){
                      folio = (String) tableModel.getValueAt(i, j);
                      System.out.println(folio);
                                               
            }
                if(folio != null){
                     try {
                    cn.RegistroDocumento(idOP,id, folio);
                   
                } catch (            ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(VistasDocumentacion.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
        
            }
              
                
               
            
        }
       
        //rs = cn.RegistroDocumento(1, id_documento, folio);
    
    }//GEN-LAST:event_AceptarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void comboOperacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboOperacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOperacionMouseClicked

    private void comboOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOperacionActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       jButton9.setEnabled(false);
        String a=(String) comboOperacion.getSelectedItem();
        System.out.println(a);
       String aux="Select * from operaciones where numeroContrato='"+d.encrypt(a)+"'";
            try {
            Statement st2;
            st2 = reg.createStatement();
            ResultSet rs2 = st2.executeQuery(aux);
            System.out.println(a);

            while (rs2.next()) {
                System.out.println(rs2.getString("id_Operacion"));
               
                idOP = Integer.parseInt(rs2.getString("id_Operacion"));
            }
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
            //jButton9.setEnabled(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void Aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aceptar1ActionPerformed
        // TODO add your handling code here:
        jButton9.setEnabled(true);
    }//GEN-LAST:event_Aceptar1ActionPerformed
 public void cargarOperacion() throws SQLException {
     Statement st1;
        try {
            st1 = reg.createStatement();
            ResultSet rs1=st1.executeQuery("Select * from operaciones");
            while(rs1.next()){
                Operacion act=new Operacion();
                act.setIdOperacion(rs1.getInt(1));
                act.setContrato(d.decrypt(rs1.getString(2)));
                act.setMonto(rs1.getDouble(3));
                act.setFecha(rs1.getString(4));
                act.setRiesgo(rs1.getDouble(5));
                act.setDescripcion(d.decrypt(rs1.getString(6)));
                act.setClienteid(rs1.getInt(7));
                act.setEmpleadoid(rs1.getInt(8));
                act.setInmobiliariaid(rs1.getInt(9));
                act.setTipoid(rs1.getInt(10));
                act.setMonedaid(rs1.getInt(11));
                act.setMonetarioid(rs1.getInt(12));
                
            comboOperacion.addItem(act);
     }
        } catch (SQLException ex) {
          System.out.println(ex);
        }
     
    }
        private void actualizarTabla() {
       
        DefaultTableModel dfm = new DefaultTableModel(){
 
            Class[] types = new Class[]{
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class,java.lang.Object.class
            };
 
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };
        tabla = this.jTable2;
        tabla.setModel(dfm);
       

       
        JCheckBox check = new JCheckBox();

        dfm.setColumnIdentifiers(new Object[]{"Numero","Documento","Entrego","Folio"});
         Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class,java.lang.Boolean.class,  java.lang.Object.class
            };
        DocumentacionDao cn = new DocumentacionDao();
        rs = cn.mostrarDatos();
      
        try{
            while(rs.next()){
                
                dfm.addRow(new Object[]{rs.getString("id_Documento"),rs.getString("descripcion"),null,null});
            }
        }catch(Exception e){
       
      
        }       
    }
        
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistasDocumentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistasDocumentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistasDocumentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistasDocumentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VistasDocumentacion().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VistasDocumentacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Aceptar1;
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox comboOperacion;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
